### ISSUE TITLE
required positional argument: 'project_dir'

### ISSUE THREAD

**Issue by gevezex** [lolipopshock/Detectron2_AL#4]
When I start the label-studio server with `label-studio server` as described in step 3.i I get this error:

```
   Project loading error
   __init__() missing 1 required positional argument: 'project_dir'
   Traceback
Traceback (most recent call last):
  File "/home/ayhan/github/Detectron2_AL/src/label-studio/label_studio/utils/misc.py", line 89, in exception_f
    return f(*args, **kwargs)
  File "/home/ayhan/github/Detectron2_AL/src/label-studio/label_studio/server.py", line 206, in welcome_page
    project = project_get_or_create()
  File "/home/ayhan/github/Detectron2_AL/src/label-studio/label_studio/server.py", line 115, in project_get_or_create
    return Project.get_or_create(input_args.project_name,
  File "/home/ayhan/github/Detectron2_AL/src/label-studio/label_studio/project.py", line 858, in get_or_create
    project = cls.get(project_name, args, context)
  File "/home/ayhan/github/Detectron2_AL/src/label-studio/label_studio/project.py", line 841, in get
    project = cls._load_from_dir(project_dir, project_name, args, context)
  File "/home/ayhan/github/Detectron2_AL/src/label-studio/label_studio/project.py", line 829, in _load_from_dir
    return cls(config, project_name, context=context, root_dir=args.root_dir)
  File "/home/ayhan/github/Detectron2_AL/src/label-studio/label_studio/project.py", line 67, in __init__
    self.load_converter()
  File "/home/ayhan/github/Detectron2_AL/src/label-studio/label_studio/project.py", line 224, in load_converter
    self.converter = Converter(self.parsed_label_config)
TypeError: __init__() missing 1 required positional argument: 'project_dir'
```

When I connect to the server I see this on the page:

```
Project loading error
__init__() missing 1 required positional argument: 'project_dir'
```

And can't do anything further. Any clue how to solve this?

**Comment by gevezex** [comment]
Solved by installing an old version of `label-studio-converter`<br>
```
pip install label-studio-converter==0.0.18
```

**Comment by lolipopshock** [comment]
And fyi, we've packaged a docker image for starting the annotation service: https://github.com/layout-Parser/annotation-service .

**Comment by gevezex** [comment]
Ooh wow, wish I knew that before. Took me a lot of time to get this working. Thnx a lot for your great effort.
