### ISSUE TITLE
Trouble following the readme

### ISSUE THREAD

**Issue by stefl14** [lolipopshock/Detectron2_AL#5]
Howdy. Great paper! I understand this isn't an actively developed repo, but I'm trying to leverage your approach for a work project (we're creating a climate search engine and have to index lots of pdfs - see https://climatepolicyradar.org/ if you're interested) and standard labelling/active learning are proving tedious. Unfortunately, I'm running into some issues.

In particular, I get the following in the labelstudio ui when I follow the readme. This is the command:

```label-studio init labeling/tk-labeling \
        --input-path="/home/stefan/Detectron2_AL/src/data" \
        --input-format=image-dir \
        --allow-serving-local-files --force \
        --label-config="/home/stefan/Detectron2_AL/annotating/config.xml" \
        --ml-backends http://localhost:9090
```
And here's the error:

```Traceback (most recent call last):
  File "/home/stefan/Detectron2_AL/src/label-studio/label_studio/utils/misc.py", line 89, in exception_f
    return f(*args, **kwargs)
  File "/home/stefan/Detectron2_AL/src/label-studio/label_studio/server.py", line 206, in welcome_page
    project = project_get_or_create()
  File "/home/stefan/Detectron2_AL/src/label-studio/label_studio/server.py", line 115, in project_get_or_create
    return Project.get_or_create(input_args.project_name,
  File "/home/stefan/Detectron2_AL/src/label-studio/label_studio/project.py", line 858, in get_or_create
    project = cls.get(project_name, args, context)
  File "/home/stefan/Detectron2_AL/src/label-studio/label_studio/project.py", line 841, in get
    project = cls._load_from_dir(project_dir, project_name, args, context)
  File "/home/stefan/Detectron2_AL/src/label-studio/label_studio/project.py", line 829, in _load_from_dir
    return cls(config, project_name, context=context, root_dir=args.root_dir)
  File "/home/stefan/Detectron2_AL/src/label-studio/label_studio/project.py", line 67, in __init__
    self.load_converter()
  File "/home/stefan/Detectron2_AL/src/label-studio/label_studio/project.py", line 224, in load_converter
    self.converter = Converter(self.parsed_label_config)
TypeError: __init__() missing 1 required positional argument: 'project_dir'
```
Would be super helpful if you could give me a quick hint as to what's wrong, though I understand you might not have looked at this in a while!

**Comment by lolipopshock** [comment]
Thanks! And so sorry I just saw your issue --  I think the error you pointed might be caused by some incompatible dependency versions (or I need to take a closer look into the readmes and commands). If you'd like to use the tool for production, you might want to take a look at this repo https://github.com/Layout-Parser/annotation-service , which we've developed a docker container to make it easy for deployment. Hope that helps!
